
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FIT5032_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Comment
{

    public int commentId { get; set; }

    public int productId { get; set; }

    public string userId { get; set; }

    public string commentDesc { get; set; }

    public int rating { get; set; }

    public Nullable<System.DateTime> commentDate { get; set; }



    public virtual Comment Comment1 { get; set; }

    public virtual Comment Comment2 { get; set; }

    public virtual Product Product { get; set; }

}

}
