
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FIT5032_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Event
{

    public int eventID { get; set; }

    public string subject { get; set; }

    public string description { get; set; }

    public System.DateTime startDate { get; set; }

    public Nullable<System.DateTime> endDate { get; set; }

    public string themeColor { get; set; }

    public Nullable<bool> isFullDay { get; set; }

}

}
