
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace FIT5032_Project.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public int orderId { get; set; }

    public Nullable<System.DateTime> dateCreated { get; set; }

    public Nullable<System.DateTime> dateShipped { get; set; }

    public Nullable<int> customerId { get; set; }

    public string orderStatus { get; set; }

    public string invoiceNumber { get; set; }

}

}
