'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Student
    Public Property Id As Integer
    Public Property FirstName As String
    Public Property LastName As String

    Public Overridable Property Units As ICollection(Of Unit) = New HashSet(Of Unit)

End Class
